/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:46439fc0-3c0c-424e-a36f-d0c5bcab8fd3",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_XZmWQfVaT",
    "aws_user_pools_web_client_id": "727hoa40oqaf713dq0c830v9q2",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "notesofpatients",
            "endpoint": "https://kdt9wnrxcj.execute-api.eu-west-3.amazonaws.com/dev",
            "region": "eu-west-3"
        }
    ],
    "aws_appsync_graphqlEndpoint": "https://3nvp22g64jevdm47t5q63bjjhu.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-alxlfndp3rfgraqj6kpdmzivgq"
};


export default awsmobile;
